### ISSUE TITLE
Import from curl fails for complex request

### ISSUE THREAD

**Issue by tutysara** [kylebebak/Requester#15]
Import from curl fails for this url

```
curl 'https://www.att.com/services/shopwireless/model/att/ecom/api/WirelessBuybackActor/getBuybackInfo?isOpup=false' -H 'accept-encoding: gzip, deflate, br' -H 'accept-language: en-US,en;q=0.9' -H 'user-agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36' -H 'accept: application/json, text/plain, */*' -H 'referer: https://www.att.com/cellphones/iphone/apple-iphone-x.html' -H 'authority: www.att.com' -H 'cookie: BVBRANDID=b1a8b47b-0148-4c37-ae28-c652d3f15417; BVBRANDSID=41c2c276-0baa-41fc-98ea-59ede98ec4f0; idse_stack=ffdc; check=true; AMCVS_55633F7A534535110A490D44%40AdobeOrg=1; idpmgw=eyJjcyI6IlVuQXV0aCIsInNpZCI6IjJIbk9SN1BZekF6SWFkbE5KQS0zM0JDSTVFQWFUQ2RJVTRFaUcyZjEzV2ciLCJjc1RrIjoiU04xTUxCN0l6bkZvNHN3WHlXdG0zbDlpRjJRTlJzd3c4L01rdz0iLCJpYXQiOjE1Mzg1MTUwNDksImV4cCI6MTUzODk0NzA0OX0.DiVoMqe2qdCk3xs4XN-TfY8UN05SobWhmtMOnZXETCs; TLTSID=DA2640D67A347946648007BC2514606A; UUID=35b79175-9192-a112-d390-8ccd0d65f16e; sto-25115-sgONEMAP_7010=MAKPAEICGCBL; HOMEPAGE_AB1101=true; SHOPSESSIONID=oL42qCDDgQYqECkFsR452pPmy6XGMKVc!-1282292663; ECOM_GTM=owffld; browserid=A003099372727; svariants=NA; cust_type=new; sto-50715-sgSHOP_7010_7011=BDEGCIIHGCBL; sto-29215-sgGOLDENEYE_8050=HCEGCIIHHCBP; SHOP_USER_ID=6260479645; SHOP_USER_CONFIRM=01c170d4b249330a943cca2ff4e1d6b1; s_cc=true; AKA_A2=A; _4c_mc_=15461391a5d2c9aeccf101993c354b38; services-common_stack_cookie=zlt08505; AAMC_att_0=REGION%7C9; aam_uuid=14162891307911286931407919707454415602; dtSa=true%7CC%7C-1%7CApple%7C-%7C1538515329421%7C115301191_832%7Chttps%3A%2F%2Fwww.att.com%2Fwireless%2F%7CAT%26T%20Wireless%20-%20Cell%20Phones%5Ec%20Plans%5Ec%20%26%20Accessories%7C1538515326363%7C; GNSESS={"UG":["Unauth"],"LOCALE":"en_US","SKA":[["1","jsp"]]}; AMCV_55633F7A534535110A490D44%40AdobeOrg=-330454231%7CMCIDTS%7C17807%7CMCMID%7C14246934990508749671435456162419356880%7CMCAAMLH-1539120134%7C9%7CMCAAMB-1539120134%7CRKhpRz8krg2tLO6pguXWp5olkAcUniQYPHaMWWgdJ3xzPWQmdj0y%7CMCOPTOUT-1538522477s%7CNONE%7CMCAID%7CNONE%7CvVersion%7C3.1.2%7CMCCIDH%7C-115961457; SALESSESSIONID=nxw2qPonmNcZx7CiDtCe4jpgFSUf53vD!1294538488; SALES_USER_ID=5553605963; SALES_USER_CONFIRM=0018a078227db2494d7ce37f26ddbdcb; sto-50715-sgSALES_7010=FOEGCIIHGCBL; _ceg.s=pfzq13; _ceg.u=pfzq13; dtCookie=LCG8BKH7POU4JD79986T55132V98QOIH|X2RlZmF1bHR8MQ; dtSa=true%7CC%7C-1%7CApple%7C-%7C1538515329421%7C115301191_832%7Chttps%3A%2F%2Fwww.att.com%2Fwireless%2F%7CAT%26T%20Wireless%20-%20Cell%20Phones%5Ec%20Plans%5Ec%20%26%20Accessories%7C1538515326363%7C; dtLatC=418; mbox=session#f87cdf1b167042779a6c400335771fac#1538517201; RT="dm=att.com&si=4hwuy2jcc1u&ss=1538515275248&sl=3&tt=25992&obo=0&sh=1538515333515%3D3%3A0%3A25992%2C1538515309170%3D2%3A0%3A22343%2C1538515288877%3D1%3A0%3A13622&rl=1"; dtPC=115330594_838h14p115338225_200h12' --compressed
```

Logs in console : 
Traceback (most recent call last):
  File "/Users/tutysara/Library/Application Support/Sublime Text 3/Installed Packages/Requester.sublime-package/commands/import_export.py", line 141, in run
    request = curl_to_request(curl)
  File "/Users/tutysara/Library/Application Support/Sublime Text 3/Installed Packages/Requester.sublime-package/commands/import_export.py", line 334, in curl_to_request
    tokens = shlex.split(curl)
  File "./python3.3/shlex.py", line 276, in split
  File "./python3.3/shlex.py", line 266, in __next__
  File "./python3.3/shlex.py", line 93, in get_token
  File "./python3.3/shlex.py", line 169, in read_token
ValueError: No closing quotation
error: Conversion Error: 'NoneType' object has no attribute 'replace'
Traceback (most recent call last):
  File "/Users/tutysara/Library/Application Support/Sublime Text 3/Installed Packages/Requester.sublime-package/commands/import_export.py", line 141, in run
    request = curl_to_request(curl)
  File "/Users/tutysara/Library/Application Support/Sublime Text 3/Installed Packages/Requester.sublime-package/commands/import_export.py", line 318, in curl_to_request
    curl = curl.replace('\\\n', '').replace('\\', '')
AttributeError: 'NoneType' object has no attribute 'replace'

**Comment by kylebebak** [comment]
Thanks for the heads up! There was an error in the parser for parsing multiple calls to `curl` from a string.

This is fixed in **2.27.1**. I'm going to close this, please let me know if you still have problems!
